server:
  port: 9527

spring:
  application:
    name: cloud-gateway
    ## GateWay配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/payment/getPayment/**  # 断言，路径相匹配的进行路由

        - id: payment_routh2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          #  uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/payment/lb/**  # 断言，路径相匹配的进行路由
#            - After=2021-01-13T15:58:19.581+08:00[Asia/Taipei]   #这个时间以后可以访问，Before,Between与After相似
#            - Cookie=username,wxq
#            - Header=X-Request-Id,\d+  #请求头必须包含X-Request-Id属性，值必须是正数的正则表达式
#            - Method=GET     #get请求
            #- Query=username, \d+  #请求参数必须包含username属性，值必须是正数的正则表达式
# 注册进 eureka Server
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true